export const ADD_ROOM = 'ADD_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';

export const UPDATE_CHAT_SUCCESS = 'UPDATE_CHAT_SUCCESS';
export const FLUSH_CHAT_MESSAGES = 'FLUSH_CHAT_MESSAGES';

export const SET_USER_NAME = 'SET_USER_NAME';


// Tic Tac Toe actions
export const SELECT_TILE = 'SELECT_TILE';
export const RESTART_GAME = 'RESTART_GAME';
