export const ADD_ROOM = 'ADD_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';

export const UPDATE_CHAT_SUCCESS = 'UPDATE_CHAT_SUCCESS';
export const FLUSH_CHAT_MESSAGES = 'FLUSH_CHAT_MESSAGES';

// Internal actions
export const SET_USER_SIGN = 'SET_USER_SIGN';
export const SET_USER_INTERNAL = 'SET_USER_INTERNAL';

// User actions
export const SET_USER = 'SET_USER';

// Tic Tac Toe actions
export const SELECT_TILE = 'SELECT_TILE';
export const RESTART_GAME_REQUEST = 'RESTART_GAME_REQUEST';
export const UPDATE_PLAYERS_LIST = 'UPDATE_PLAYERS_LIST';
export const ADD_PLAYER_TO_GAME = 'ADD_PLAYER_TO_GAME';
export const REMOVE_PLAYER_FROM_GAME = 'REMOVE_PLAYER_FROM_GAME';
// export const SWITCH_TURN = 'SWITCH_TURN';

export const INIT_STATE = 'INIT_STATE';
export const ADD_USER_TO_ROOM = 'ADD_USER_TO_ROOM';
export const REMOVE_USER_FROM_ROOM = 'REMOVE_USER_FROM_ROOM';
export const ROTATE_TURN = 'ROTATE_TURN';
