export const ADD_ROOM = 'ADD_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';

export const UPDATE_CHAT_SUCCESS = 'UPDATE_CHAT_SUCCESS';
